# Dockerfile
FROM  golang:1.23-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X main.version=v1.0" -o /bit/qr

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata && update-ca-certificates
COPY --from=builder /bin/qr /usr/local/bin/
EXPOSE 8080
CMD ["qr", "-http"]
